### ISSUE TITLE
Why init beta needs sqrt?

### ISSUE THREAD

**Issue by fishfishson** [ventusff/neurecon#6]
Hi, 

Thx for your excellent repo. In volsdf rendering part, I find you add extra sqrt when initializing beta which does not show in volsdf paper's equation. Could you pls tell me why you use sqrt here?

**Comment by ventusff** [comment]
Hi,
This is a good question :) This part is my biggest confusion when implementing VolSDF.

It is mainly about how to deal with alpha and beta simultaneously.

In VolSDF's paper, the upsample algorithm choose a suitable initial beta that promises the error bound, which is written as:
![image](https://user-images.githubusercontent.com/25529198/140479566-60e80556-3863-48f7-b682-1abfc0507359.png)

However, the **alpha** in the numerator on the right side is actually undefined in the paper and is unclear. I've tried with using the network's alpha (which is `self.forward_ab()[0]`), but that will cause the upsampling algorithm completely fail to produce reasonable results.

Considering that this expression is derived assuming corresponding alpha and beta (by "corresponding", I mean `alpha=1/beta`, which is stated in Sec3.5. in VolSDF's paper), the expression above could be further derived as follow:
![image](https://user-images.githubusercontent.com/25529198/140481042-1fbd2451-5125-441e-8819-10cdf9208f03.png)
Hence produce the `sqrt` operation.

**Comment by fishfishson** [comment]
@ventusff Great answer! I got it.
